server:
  port: 10000
spring:
  redis:
    host: 192.168.202.134
    port: 6379
    password: root1234
  application:
    name: Gateway
  cloud:
    discovery:
      nacos:
        server-addr: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        - id: BookKeepingProvider
          uri: lb://BookKeepingProvider
          predicates:
            - Path=/book/keeping/**
        - id: UploadProvider
          uri: lb://UploadProvider
          predicates:
            - Path=/upload/**
        - id: AuthenticationProvider
          uri: lb://AuthenticationProvider
          predicates:
            - Path=/authentication/**
        - id: TodoListProvider
          uri: lb://TodoListProvider
          predicates:
            - Path=/todo/**
health:
  auth:
    excludePaths:
      - /authentication/**